{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nd-common.fullname" . }}
  labels:
    {{- include "nd-common.extendedLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nd-common.selectorLabels" . | nindent 8 }}
  {{ toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
