{{- $rolloutZones := default (list "default") .Values.rolloutZones }}
{{- if .Values.rolloutZonesTransition }}
{{- $rolloutZones = prepend $rolloutZones "default" }}
{{- end }}

{{- $fullName := include "nd-common.fullname" . }}
{{- $rolloutZoneLabel := "" }}


{{- range $rolloutZone := index $rolloutZones }}

{{- if ne $rolloutZone "default" }}
{{- $fullName                  = printf "%s-%s" (include "nd-common.fullname" $) $rolloutZone }}
{{- $topologyKey               := required ".Values.rolloutZones requires that .Values.topologyKey is also set" $.Values.topologyKey }}
{{- $rolloutZoneLabel          = printf "%s: %s" $topologyKey $rolloutZone }}
{{- else }}
{{- $fullName                  = include "nd-common.fullname" $ }}
{{- end }}

---
{{- if $.Values.podDisruptionBudget -}}
{{- if and $.Values.replicaCount (lt ($.Values.replicaCount | int) 2) }}
{{- fail "Deployment replica count can not be less than 2 in order to configure PDB. Please configure Replica count greater than or equal to 2." }}
{{- end }}
{{- if and $.Values.autoscaling.enabled (lt ($.Values.autoscaling.minReplicas | int) 2) }}
{{- fail "Deployment autoscaling minimum can not be less than 2 in order to configure PDB. Please configure a minimum replica count greater than or equal to 2." }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rollout-app.labels" $ | nindent 4 }}
    {{- with $rolloutZoneLabel }}
    {{ . }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nd-common.selectorLabels" $ | nindent 6 }}
      {{- with $rolloutZoneLabel }}
      {{ . }}
      {{- end }}
  {{ toYaml $.Values.podDisruptionBudget | nindent 2 }}
{{- end }}

{{- end }}
