---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nd-common.serviceName" . }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
  annotations:
    {{/*
    This is only used for type=LoadBalancer Services which run in AWS.
    */}}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes_namespace={{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "rollout-app.servicePorts" . | nindent 4 }}
  selector:
    {{- include "nd-common.selectorLabels" . | nindent 4 }}
---
{{/*
This optional "Canary" service is created only when the .Values.strategy is set
to "canary". Rollouts will then use this service to route canary traffic to, in
order to test releases.
When using Istio VirtualServices (if .Values.virtualService.enabled=true), the
VirtualService will be configured to use this Service as the canary service,
and it will automatically adjust the weights to move traffic between the stable
and canary service.
*/}}
{{- if eq .Values.strategy "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nd-common.serviceName" . }}-canary
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
  annotations:
    {{/*
    This is only used for type=LoadBalancer Services which run in AWS.
    */}}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes_namespace={{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "rollout-app.servicePorts" . | nindent 4 }}
  selector:
    {{- include "nd-common.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{/*
This optional "Preview" service is created when the .Values.strategy is set to
"blueGreen". The intention is that this service is used either for running
experiments against, or for humans to manually test and verify before allowing
a deployment to continue.
https://argoproj.github.io/argo-rollouts/features/bluegreen/#previewservice
*/}}
{{- if eq .Values.strategy "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nd-common.serviceName" . }}-preview
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
  annotations:
    {{/*
    This is only used for type=LoadBalancer Services which run in AWS.
    */}}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes_namespace={{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "rollout-app.servicePorts" . | nindent 4 }}
  selector:
    {{- include "nd-common.selectorLabels" . | nindent 4 }}
{{- end }}
---
