---
{{- /*
Role to define additional access needed for workflow
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-workflow-custom-access
  annotations:
    workflows.argoproj.io/description: |
      Recomended minimum permissions for `pns` executor.
    workflows.argoproj.io/version: "< 3.4.0"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - update
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - get
---
{{- /*
Role binding to allow access to workflow service account.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-workflow-custom-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-workflow-custom-access
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workflow.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
