{{- if and .Values.ingress.enabled .Values.ports }}
{{- if gt (len .Values.ports) 0 }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nd-common.fullname" . }}-ingress-access
  labels:
    {{- include "nd-common.extendedLabels" . | nindent 4 }}
spec:
  policyTypes: [Ingress]
  podSelector:
    matchLabels:
      {{- include "nd-common.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
      {{- range $port := .Values.ports }}
      - port: {{ $port.containerPort }}
        protocol: {{ $port.protocol }}
      {{- end }}
{{- end }}
{{- end }}
