# This identifies all of the resources as belonging to this particular chart,
# even though they will ultimately be named likely by the parent chart that
# uses this as a dependency.
chart_name: istio-alerts
chart_source: https://github.com/Nextdoor/k8s-charts

# Defaults applied to all Prometheus Rules
defaults:
  # -- The prefix URL to the runbook_urls that will be applied to each PrometheusRule
  runbookUrl: https://github.com/Nextdoor/k8s-charts/blob/main/charts/istio-alerts/runbook.md
  # -- Additional custom labels attached to every PrometheusRule
  additionalRuleLabels: {}

# Service Rules
#
# These rules provide some basic alerting around performance of any VirtualServices
# in the target namespace.
#
serviceRules:
  # -- Whether to enable the service rules template
  enabled: true

  # -- Narrow down the alerts to a particular Destination Service if there
  # are multiple services that require different thresholds within the same
  # namespace.
  destinationServiceName: .*

  # -- Configuration related to the 5xx monitor for the VirtualService.
  http5XXMonitor:
    # -- Whether to enable the monitor on 5xxs returned by the VirtualService.
    enabled: true

    # -- How long to evaluate the rate of 5xxs over.
    for: 5m

    # -- The threshold for considering the 5xx monitor to be alarming. Default
    # is 0.05% error rate, i.e 99.95% reliability.
    threshold: 0.0005

    # -- Severity of the 5xx monitor
    severity: critical

    # -- The set of labels to use when evaluating the ratio of the 5XX.
    monitorGroupingLabels:
      - destination_service_name
      - reporter

  # -- Configuration related to the latency monitor for the VirtualService.
  highRequestLatency:
    # -- Whether to enable the monitor on latency returned by the
    # VirtualService.
    enabled: true

    # -- Which percentile to monitor - should be between 0 and 1. Default is
    # 95th percentile.
    percentile: 0.95

    # -- Severity of the latency monitor
    severity: warning

    # -- The threshold for considering the latency monitor to be alarming. This
    # is in seconds.
    threshold: 0.5

    # -- How long to evaluate the latency of services.
    for: 15m

  # -- Does a basic lookup using the defined selectors to see if we can see any
  # info for a given selector. This is the "watcher for the watcher". If we get
  # alerted by this, we likely have a bad selector and our alerts are not going
  # to ever fire.
  destinationServiceSelectorValidity:
    # -- Whether to enable the monitor on the selector for the VirtualService.
    enabled: true

    # -- Severity of the monitor
    severity: warning

    # -- How long to evaluate.
    for: 1h
