{{ if and .Values.alertManager.enabled .Values.alertManager.pagerduty }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Release.Name }}-default-pagerduty
  labels:
    alertmanagerConfig: {{ .Values.alertManager.alertmanagerConfig }}
spec:
  route:
    groupBy:
{{ .Values.alertManager.groupBy | toYaml | indent 6 }}
    groupWait: {{ .Values.alertManager.groupWait }}
    groupInterval: {{ .Values.alertManager.groupInterval }}
    repeatInterval: {{ .Values.alertManager.repeatInterval }}
    receiver: pagerduty  # this name is scoped to within this AlertmanagerConfig object
  receivers:
    - name: pagerduty
      pagerdutyConfigs:
        - sendResolved: true
          severity: '{{ .Files.Get "files/pagerduty_severity.tpl" | trimSuffix "\n" }}'
          routingKey:
            name: {{ .Release.Name }}-default-pagerduty-routing-key
            key: routing_key
{{ end -}}
