{{ if and .Values.alertManager.enabled .Values.alertManager.pagerduty }}
{{ if .Values.alertManager.pagerduty.routing_key_parameter }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-default-pagerduty-routing-key
spec:
  backendType: systemManager
  data:
    - key: {{ .Values.alertManager.pagerduty.routing_key_parameter }}
      name: routing_key
{{ else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-pagerduty-routing-key
type: Opaque
data:
  routing_key: {{ .Values.alertManager.pagerduty.routing_key | b64enc }}
{{ end -}}
{{ end -}}
