apiVersion: v2
name: simple-app
description: Default Microservice Helm Chart
type: application
version: 0.23.1
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.1.3
    repository: https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: prometheus-alerts
    version: 1.0.2
    alias: alerts
    repository: https://k8s-charts.nextdoor.com
    condition: alerts.enabled
  - name: nd-common
    version: 0.0.15
    repository: file://../nd-common
