apiVersion: v2
name: simple-app
description: Default Microservice Helm Chart
type: application
version: 0.16.0
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:

  - name: istio-alerts
    alias: istioRules
    version: 0.1.2
      #repository: https://k8s-charts.nextdoor.com
    repository: file://../istio-alerts/
    condition: istioRules.enabled
