apiVersion: v2
name: simple-app
description: Default Microservice Helm Chart
type: application
version: 1.11.0
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.5.2
    repository: https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: nd-common
    version: 0.3.2
    repository: file://../nd-common
