apiVersion: v2
name: simple-app
description: Default Microservice Helm Chart
type: application
version: 1.13.2
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.5.3
    repository: file://../istio-alerts  # https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: nd-common
    version: 0.4.2
    repository: file://../nd-common
