apiVersion: v2
name: simple-app
description: Default Microservice Helm Chart
type: application
version: 0.25.10
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.1.3
    repository: https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: nd-common
    version: 0.0.20
    repository: file://../nd-common
