apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: {{ template "flink-job-cluster.fullname" . }}
  labels:
    {{- include "flink-job.labels" . | nindent 4 }}
spec:
  {{- with .Values.flinkVersion }}
  flinkVersion: {{ . }}
  {{- end }}
  image:
    name: {{ template "flink-job-cluster.imageFqdn" . }}
    pullPolicy: IfNotPresent
  batchSchedulerName: {{ .Values.batchSchedulerName }}
  envVars:
    {{- toYaml .Values.envVars | nindent 4 }}
  serviceAccountName: {{ template "flink-job-cluster.fullname" . }}
  recreateOnUpdate: {{ .Values.recreateOnUpdate }}
  jobManager:
    replicas: {{ .Values.jobManager.replicas }}
    accessScope: {{ .Values.jobManager.accessScope }}
    ports:
      ui: {{ .Values.jobManager.ports.ui }}
      rpc: {{ .Values.jobManager.ports.rpc }}
      query: {{ .Values.jobManager.ports.query }}
      blob: {{ .Values.jobManager.ports.blob }}
    {{- if .Values.jobManager.metrics.enabled }}
    extraPorts:
      {{- toYaml .Values.jobManager.metrics.extraPorts | nindent 6 }}
    {{- end }}
    # TODO (Aaron/Albert) expose ingress?
    resources:
      {{- toYaml .Values.jobManager.resources | nindent 6 }}
    # TODO (Aaron/Albert) expose memory configs?
    {{- if or (.Values.jobManager.volumes) (.Values.savepoints.enabled) }}
    volumes:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        persistentVolumeClaim:
          claimName: {{ template "flink-job-cluster.fullname" . }}-savepoint
      {{- end }}
      {{- with .Values.jobManager.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.jobManager.volumeMounts) (.Values.savepoints.enabled) }}
    volumeMounts:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        mountPath: {{ .Values.savepoints.savepointDir }}
      {{- end }}
      {{- with .Values.jobManager.volumeMounts }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if .Values.jobManager.volumeClaimTemplates }}
    volumeClaimTemplates:
      {{ toYaml .Values.jobManager.volumeClaimTemplates | nindent 6}}
    {{- end }}
    # initContainers, sideCars not exposed
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    podAnnotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    podLabels:
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  # securityContext, livenessProbe, readinessProbe not exposed
    memoryProcessRatio: {{ .Values.jobManager.memoryProcessRatio }}
  taskManager:
    ports:
      data: {{ .Values.taskManager.ports.data }}
      rpc: {{ .Values.taskManager.ports.rpc }}
      query: {{ .Values.taskManager.ports.query }}
    replicas: {{ .Values.taskManager.replicas }}
    {{- if or (.Values.taskManager.volumes) (.Values.savepoints.enabled) }}
    volumes:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        persistentVolumeClaim:
          claimName: {{ template "flink-job-cluster.fullname" . }}-savepoint
      {{- end }}
      {{- if .Values.taskManager.volumes }}
      {{- toYaml .Values.taskManager.volumes | nindent 6}}
      {{- end }}
    {{- end }}
    {{- if or (.Values.taskManager.volumeMounts) (.Values.savepoints.enabled) }}
    volumeMounts:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        mountPath: {{ .Values.savepoints.savepointDir }}
      {{- end }}
      {{- if .Values.taskManager.volumeMounts }}
      {{- toYaml .Values.taskManager.volumeMounts | nindent 6}}
      {{- end }}
    {{- end }}
    {{- if .Values.taskManager.volumeClaimTemplates }}
    volumeClaimTemplates:
      {{ toYaml .Values.taskManager.volumeClaimTemplates | nindent 6}}
    {{- end }}
    {{- if .Values.taskManager.metrics.enabled }}
    extraPorts:
      {{- toYaml .Values.taskManager.metrics.extraPorts | nindent 6 }}
    {{- end }}
    resources:
      {{- toYaml .Values.taskManager.resources | nindent 6 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    podAnnotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    podLabels:
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    securityContext:
      {{- toYaml .Values.taskManager.securityContext | nindent 6 }}
    memoryProcessRatio: {{ .Values.taskManager.memoryProcessRatio }}
  job:
    mode: {{ .Values.job.mode }}
    jarFile: {{ .Values.job.jarFile }}
    className: {{ .Values.job.className }}
    args: {{ .Values.job.args }}
    {{- if .Values.job.fromSavepoint }}
    fromSavepoint: {{ .Values.job.fromSavepoint }}
    {{- end}}
    autoSavepointSeconds: {{ .Values.job.autoSavepointSeconds }}
    savepointsDir: {{ .Values.job.savepointsDir }}
    allowNonRestoredState: {{ .Values.job.allowNonRestoredState }}
    takeSavepointOnUpdate: {{ .Values.job.takeSavepointOnUpdate }}
    {{- if .Values.job.savepointGeneration }}
    savepointGeneration: {{ .Values.job.savepointGenaration }}
    {{- end }}
    noLoggingToStdout: false
    parallelism: {{ .Values.job.parallelism }}
    restartPolicy: {{ .Values.job.restartPolicy }}
    cleanupPolicy:
      afterJobFails: {{ .Values.job.cleanupPolicy.afterJobSucceeds}}
      afterJobCancelled: {{ .Values.job.cleanupPolicy.afterJobSucceeds}}
      afterJobSucceeds: {{ .Values.job.cleanupPolicy.afterJobSucceeds}}
    {{- if or (.Values.job.volumes) (.Values.savepoints.enabled) }}
    volumes:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        persistentVolumeClaim:
          claimName: {{ template "flink-job-cluster.fullname" . }}-savepoint
      {{- end }}
      {{- if .Values.job.volumes }}
      {{- toYaml .Values.job.volumes | nindent 6}}
      {{- end }}
    {{- end }}
    {{- if or (.Values.job.volumeMounts) (.Values.savepoints.enabled) }}
    volumeMounts:
      {{- if .Values.savepoints.enabled }}
      - name: savepoint-storage
        mountPath: {{ .Values.savepoints.savepointDir }}
      {{- end }}
      {{- if .Values.job.volumeMounts }}
      {{- toYaml .Values.job.volumeMounts | nindent 6}}
      {{- end }}
    {{- end }}
    {{- if .Values.job.initContainers.enabled }}
    initContainers:
    - name: {{ .Chart.Name}}-python-blob-downloader
      image: "{{ .Values.job.initContainers.image }}:{{ .Values.job.initContainers.tag }}"
      command: ["/bin/sh","-c","--"]
      args: ["/app/exec-python.sh"]
      env: 
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.job.initContainers.Storage.secretName }}
              key: {{ .Values.job.initContainers.Storage.secretNameKey }}
        - name: CONTAINER_NAME
          value: {{ .Values.job.initContainers.Storage.containerName }}
        - name: BLOB_NAME
          value: {{ .Values.job.initContainers.Storage.blobName }}
    {{- end }} 
    podAnnotations:
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    podLabels:
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  logConfig:
    {{- toYaml .Values.logConfig | nindent 4}}
  flinkProperties:
    {{- with .Values.flinkProperties }}
    {{- range $property, $value := index . }}
    {{ $property }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- end }}
