apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows the service account to read / write / delete config maps
# in the current namespace.
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-ha-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "flink-job-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-ha-jobmanager
  apiGroup: rbac.authorization.k8s.io
