apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows oncall engineers to patch configmaps.
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  {{- range $group := .Values.operatorGroups }}
  - kind: Group
    name: {{ $group }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-operator
  apiGroup: rbac.authorization.k8s.io
