apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows oncall engineers to patch configmaps.
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: nd:oncall
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-operator
  apiGroup: rbac.authorization.k8s.io
