{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "flink-job-cluster.fullname" . }}
  {{- if .Values.podMonitor.podMonitorSelectorLabels }}
  labels:
    {{- toYaml .Values.podMonitor.podMonitorSelectorLabels | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podTargetLabels:
    {{- toYaml .Values.podMonitor.podTargetLabels | nindent 4 }}
  selector:
    matchLabels:
      app: flink
  podMetricsEndpoints:
    - port: {{ .Values.podMonitor.portName }}
      interval: {{ .Values.podMonitor.scrapeInterval }}
      {{- with .Values.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.podMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end -}}
{{- end -}}

---

{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "flink-job-cluster.fullname" . }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.podMonitor.podMonitorSelectorLabels }}
  labels:
    {{- toYaml .Values.podMonitor.podMonitorSelectorLabels | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: {{ template "flink-job-cluster.fullname" . }}.monitorRules
    rules:
      - record: pod_monitor_sample_limit
        expr: {{ (default 25000 .Values.podMonitor.sampleLimit) | quote }}
        labels:
          namespace: {{ .Release.Namespace }}
          name: {{ template "flink-job-cluster.fullname" . }}
          instance: {{ .Release.Name }}
{{- end }}
