{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "flink-job-cluster.fullname" . }}
  {{- if .Values.podMonitor.podMonitorSelectorLabels }}
  labels:
    {{- toYaml .Values.podMonitor.podMonitorSelectorLabels | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podTargetLabels:
    {{- toYaml .Values.podMonitor.podTargetLabels | nindent 4 }}
  selector:
    matchLabels:
      app: flink
  podMetricsEndpoints:
    - port: {{ .Values.podMonitor.portName }}
      interval: {{ .Values.podMonitor.scrapeInterval }}
      {{- with .Values.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.podMonitor.SampleLimit }}
  SampleLimit: {{ . }}
  {{- end -}}
{{- end -}}
