{{- if .Values.serviceAccount.create -}}
{{- if .Values.flavors -}}
{{ $global := . }}
{{ range $flavor, $cfg := index .Values.flavors }}
{{ $values := mergeOverwrite (deepCopy $global) $cfg }}
{{ $_ := set $values "flavor" $flavor }}
{{- if or (not (hasKey $values.Values "enabled")) $values.Values.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flink-job.serviceAccountName" $values }}
{{- end -}}
{{- end -}}
{{- else -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flink-job.serviceAccountName" . }}
{{- end -}}
{{- end -}}
