apiVersion: v2
appVersion: "1.0"
description: Intalls the Spotify-version of the Flink-on-K8S-Operator
name: flink-operator
version: 0.0.1
sources:
  - https://github.com/spotify/flink-on-k8s-operator/releases
