flink-operator-crd:
  # -- (`bool`) whether or not to enable flink-operator-crd chart
  enabled: false

# -- (`int`) Number of FlinkOperator pods to run. If set to > 1, then
# leaderElection should also be enabled.
replicas: 1

image:
  # -- (`string`) The Docker Image to pull for the operator. Override to pull a custom image.
  repository: ghcr.io/spotify/flink-operator

  # -- (`string`) The Docker Image Tag to pull - defaults to the Chart AppVersion value in Chart.yaml.
  tag:

# -- (`map`) Custom compute resources to apply to the `manager` container
# within the controller pod.
resources:

# -- (`map`) Optional nodeSelector for the manager pod
nodeSelector: {}

rbacProxy:
  image:
    # -- (`string`) The Docker Image to pull for the sidecar that provides
    # secure authentication into the Flink Operator pod for the Kubernetes API.
    repository: gcr.io/kubebuilder/kube-rbac-proxy

    # -- (`string`) The Docker Tag to use
    tag: v0.8.0

  # -- (`map`) Custom compute resources to apply to the `kube-rbac-proxy` container
  # within the controller pod.
  resources:

  # -- (`int`) The verbosity level to set logging to.
  logLevel: 10

podMonitor:
  # -- (`bool`) whether or not to enable pod monitor
  enabled: true

leaderElection:
  # -- (`bool`) Whether or not to enable Leader Election. This can be disabled
  # - but should generally be enabled because it provides safe rollouts of new
  # Flink Operator pods.
  enabled: true

  # -- (`string` The name of the Lease to hold if Leader Election is enabled.
  name: flink-operator-lock

mutatingWebhook:
  # -- (`bool`) Whether or not to create the MutatingWebhookConfiguration.
  # Optionally disable-able if you are installing in a non-privileged
  # environment where you cannot create Cluster-scoped resources.
  enabled: true

validatingWebhook:
  # -- (`bool`) Whether or not to create the ValidatingWebhookConfiguration.
  # Optionally disable-able if you are installing in a non-privileged
  # environment where you cannot create Cluster-scoped resources.
  enabled: true

# -- (`bool`) If enabled, then the Flink Operator will be scoped to watch only
# this local namespace. If this is set to `false` then all of the `Roles1 and
# `RoleBindings` will be namespace scoped. If this is set to True, then they
# will be converted to `ClusterRoles` and ClusterRoleBindings`.
namespaceScoped: false

tests:
  enabled: false

# Used for CI testing or local delopment if the cert-manager is not already
# installed. This is required for the kube-rbac-proxy to have a proper SSL
# endpoint.
cert-manager:
  # -- (`string`) Whether or not to install the Jetstack Cert-Manager. If
  # false, you must have this installed already in your cluster.
  enabled: false
