{{- if .Values.virtualService.enabled }}
{{- $global := . }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ .Values.virtualService.namespace }}/{{ .Values.virtualService.gateway }}
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ tpl . $global | quote }}
    {{- end }}
  {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute */}}
  http:
    - match:
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest */}}
      - uri:
          prefix: {{ .Values.virtualService.path }}
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination */}}
      route:
        - destination:
            host: {{ include "simple-app.fullname" . }}
            port:
              number: {{ .Values.virtualService.port }}
  {{- with .Values.virtualService.tls }}
  tls:
    {{- tpl . $global | nindent 4 }}
  {{- end }}
{{- end }}
