{{- if .Values.virtualService.enabled }}
{{- $global := . }}
{{- $istioNs := .Values.virtualService.namespace }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.virtualService.gateways }}
  gateways:
    {{- range $gw := . }}
    - {{ $istioNs }}/{{ $gw }}
    {{- end }}
  {{- end }}
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ tpl . $global | quote }}
    {{- end }}
  {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute */}}
  http:
    - match:
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest */}}
      {{- with .Values.virtualService.matches }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest */}}
      {{- if .Values.virtualService.paths }}
      {{- range $path := .Values.virtualService.paths }}
      - uri:
          prefix: {{ $path }}
      {{- end }}
      {{- else }}
      - uri:
          prefix: {{ .Values.virtualService.path }}
      {{- end }}
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy */}}
      {{- with .Values.virtualService.corsPolicy }}
      corsPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- /* https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination */}}
      route:
        - destination:
            host: {{ include "simple-app.fullname" . }}
            port:
              number: {{ .Values.virtualService.port }}
  {{- with .Values.virtualService.tls }}
  tls:
    {{- tpl . $global | nindent 4 }}
  {{- end }}
{{- end }}
