{{- if .Capabilities.APIVersions.Has "datadoghq.com/v1alpha1" -}}
{{-  range $name, $monitor := .Values.monitors }}
{{- if not (eq $monitor.enabled false) }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ $name }}
  labels: {{- include "nd-common.labels" $ | nindent 4 }}
spec:
  name: {{ $monitor.name | quote }}
  message: {{ $monitor.message | quote }}
  query: {{ $monitor.query  | quote }}
  type: {{ default "query alert" $monitor.type | quote }}
  {{- with $monitor.priority }}
  priority: {{.}}
  {{- end }}
  tags: {{ include "datadog-monitors.tags" (list $ .tags) | nindent 4 }}
  options:
    locked: false
    {{- with $monitor.options }}{{ toYaml . | nindent 4 }}{{- end }}
{{- end }}
{{- end }}
{{- end }}
