apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
    control-plane: controller-manager
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --zap-devel=false
        command:
        - /flink-operator
        image: {{ include "flink-operator.imageFqdn" . }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            #cpu: 100m
            #memory: 30Mi
            memory: 256Mi
          requests:
            #cpu: 100m
            #memory: 20Mi
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v={{ .Values.logLevel }}
        - --enable-leader-election={{ .Values.leaderElection.enabled }}
        - --leader-election-id={{ .Values.leaderElection.name }}
        {{- if .Values.namespaceScoped }}
        - --watch-namespace={{ .Release.Namespace }}
        {{- end }}
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      securityContext:
        runAsNonRoot: false
      serviceAccountName: flink-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-webhook-server-cert
