{{- if .Values.mutatingWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  name: {{ .Release.Name }}-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-flinkoperator-k8s-io-v1beta1-flinkcluster
  failurePolicy: Fail
  name: mflinkcluster.flinkoperator.k8s.io
  rules:
  - apiGroups:
    - flinkoperator.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
  sideEffects: None
{{- end }}
