---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-to-operator
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes: [Ingress]
  ingress:
    - ports:
      - port: 9443
        protocol: TCP
