{{ if .Values.podMonitor.enabled }}
# see https://raw.githubusercontent.com/GoogleCloudPlatform/flink-on-k8s-operator/master/examples/prometheus/flink_metric_cluster.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  podTargetLabels:
    - cluster
    - component
  selector:
    matchLabels:
      app: flink
  # Specify the port name of the exposed metric port
  podMetricsEndpoints:
    - port: prom
{{ end -}}

---

{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.podMonitor.podMonitorSelectorLabels }}
  labels:
    {{- toYaml .Values.podMonitor.podMonitorSelectorLabels | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: {{ .Release.Name }}
    rules:
      - record: pod_monitor_sample_limit
        expr: {{ (default 25000 .Values.podMonitor.sampleLimit) | quote }}
        labels:
          namespace: {{ .Release.Namespace }}
          name: {{ .Release.Name }}
          instance: {{ .Release.Name }}
{{- end }}
