apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.namespaceScoped }}RoleBinding{{ else }}ClusterRoleBinding{{- end }}
metadata:
  name: {{ .Release.Name }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.namespaceScoped }}Role{{ else }}ClusterRole{{- end }}
  name: {{ .Release.Name }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
