apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes_namespace={{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
