apiVersion: v2
name: stateful-app
description: Default StatefulSet Helm Chart
type: application
version: 1.0.1
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.4.0
    repository: https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: nd-common
    version: 0.3.1
    repository: https://k8s-charts.nextdoor.com
