apiVersion: v2
name: stateful-app
description: Default StatefulSet Helm Chart
type: application
version: 0.9.2
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: istio-alerts
    version: 0.1.3
    repository: https://k8s-charts.nextdoor.com
    condition: istio-alerts.enabled
  - name: nd-common
    version: 0.0.18
    repository: file://../nd-common
