# For local development, we turn on the Ingress controller and set up a simple
# local ingress.
ingress:
  # -- Enable local ingress for local development.
  enabled: true

  # -- Disable the SSL-Redirect explicitly because it only applies to
  # ALB-ingress controllers.
  sslRedirect: false

topologyKey: kubernetes.io/hostname
enableTopologySpread: true
terminationGracePeriodSeconds: 30
datadog:
  scrapeMetrics: true
  scrapeLogs:
    enabled: true
