{{ if and .Values.alertManager.enabled .Values.alertManager.pagerduty }}
{{ if and .Values.alertManager.pagerduty.routing_key_parameter .Values.alertManager.pagerduty.routing_key_store_ref }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-default-pagerduty-routing-key
spec:
  secretStoreRef:
    {{- toYaml .Values.alertManager.pagerduty.routing_key_store_ref | nindent 4 }}
  target:
    name: {{ .Release.Name }}-default-pagerduty-routing-key
  data:
    - secretKey: routing_key
      remoteRef:
        key: {{ .Values.alertManager.pagerduty.routing_key_parameter }}
{{ else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-pagerduty-routing-key
type: Opaque
data:
  routing_key: {{ .Values.alertManager.pagerduty.routing_key | b64enc }}
{{ end -}}
{{ end -}}
