{{- if .Values.sidecar.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ include "istio-endpoints.fullname" . }}-proxy-config
  labels:
    {{- include "istio-endpoints.labels" . | nindent 4 }}
  {{- with .Values.sidecar.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  workloadSelector:
    labels:
      {{- include "istio-endpoints.selectorLabels" . | nindent 6 }}
  egress:
    {{- /*
    For each ElastiCache endpoint, we create a specific Listener configuration
    here in the Egress key. These listeners are what configure the istio-proxy
    container to specifically bind to an "IP:PORT", and route traffic to a
    specific ServiceEndpoint entry.
    */}}
    {{- /*
    The default Egress capture uses the iptables capturemode and collects all
    of the ServiceEntries, Services, etc in the entire cluster. This behavior
    can be customized though.
    */}}
    - # Default CatchAll
      captureMode: {{ $.Values.sidecar.catchAllCaptureMode }}
      hosts:
        {{- toYaml $.Values.sidecar.catchAllHosts | nindent 8 }}
{{- end }}
