# For local development, we turn on the Ingress controller and set up a simple
# local ingress.
ingress:
  # -- Enable local ingress for local development.
  enabled: true

  # -- Disable the SSL-Redirect explicitly because it only applies to
  # ALB-ingress controllers.
  sslRedirect: false

livenessProbe:
  httpGet:
    path: /
    port: 80

readinessProbe:
  httpGet:
    path: /
    port: 80

command:
  - /bin/sleep
  - infinity

proxySidecar:
  enabled: true
  image:
    repository: nginx
    tag: stable

replicaCount: 2
minReadySeconds: 2
progressDeadlineSeconds: 90
terminationGracePeriodSeconds: 5
