# https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-ephemeral.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  {{- with .Values.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  kafka:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 60
      failureThreshold: 30  # 30 * 10s
    readinessProbe:
      initialDelaySeconds: 60
      failureThreshold: 30  # 30 * 10s
    authorization:
      type: simple
    jvmOptions:
      '-Xmx': '384M'
      '-Xms': '128M'
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
      - name: plain
        port: 9093
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 500Mi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 500Mi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
