apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  {{- with .Values.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  kafka:
    {{- with .Values.kafka.brokerVersion }}
    version: {{ . }}
    {{- end }}
    {{- with .Values.kafka.priorityClassName }}
    template:
      pod:
        priorityClassName: {{ . }}
    {{- end }}
    replicas: 1
    authorization:
      type: simple
      superUsers:
        - ANONYMOUS
    jvmOptions:
      '-Xmx': '384M'
      '-Xms': '128M'
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
      - name: plain
        port: 9093
        type: internal
        tls: false
      {{- toYaml .Values.listeners | nindent 6 }}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      {{- with .Values.kafka.logMessageFormatVersion }}
      log.message.format.version: "{{ . }}"
      {{- end }}
      {{- with .Values.kafka.interBrokerProtocolVersion }}
      inter.broker.protocol.version: "{{ . }}"
      {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          annotations:
            {{- with .Values.annotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
