serviceName: eks
team: cloudeng
monitors:
  failed-pods:
    disabled: true
    name: "[kubernetes] Monitor Kubernetes Failed Pods in Namespaces"
    message: "More than ten pods are failing in ({{kube_cluster_name.name}} cluster). \n The threshold of ten pods varies depending on your infrastructure. Change the threshold to suit your needs."
    priority: "2"
    query: "change(avg(last_5m),last_5m):sum:kubernetes_state.pod.status_phase{phase:failed} by {kube_cluster_name,kube_namespace} > 10"
    type: "query alert"
  datadog-log-alert-test:
    query: "logs(\"source:nagios AND status:error\").index(\"default\").rollup(\"count\").last(\"1h\") > 5"
    type: "log alert"
    name: "Test log alert made from DatadogMonitor"
    message: "1-2-3 testing"
    tags:
      test: datadog
      team: data
    priority: 5
    options:
      enableLogsSample: true
      evaluationDelay: 300
      includeTags: true
      locked: false
      notifyNoData: true
      noDataTimeframe: 30
      renotifyInterval: 1440
