{{ $global := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- range $annotation, $value := index . }}
        {{ $annotation }}: {{ tpl $value $global | quote }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "simple-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $global | nindent 4 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simple-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.volumes .Values.volumesString }}
      volumes:
        {{- with .Values.volumes }}{{ toYaml . | nindent 8 }}{{ end }}
        {{- with .Values.volumesString }}{{ tpl . $global | nindent 8 }}{{ end }}
      {{- end }}
      containers:
        {{- if .Values.proxySidecar.enabled }}
        - name: {{ .Values.proxySidecar.name }}
          image: "{{ .Values.proxySidecar.image.repository }}:{{ .Values.proxySidecar.image.tag }}"
          imagePullPolicy: {{ .Values.proxySidecar.image.pullPolicy }}
          {{- with .Values.proxySidecar.envFrom }}
          envFrom:
            {{- range $env := index .}}
            {{- with $env.configMapRef }}
            - configMapRef:
                name: {{ tpl (required ".name key must be set in configMapRef" .name) $global }}
            {{- end }}
            {{- with $env.secretRef }}
            - secretRef:
                name: {{ tpl (required ".name key must be set on secretRef" .name) $global }}
            {{- end }}
            {{- end }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxySidecar.env }}
          env:
            {{- range $env := index . }}
            - name: {{ tpl $env.name $global }}
              {{- if $env.value }}
              value: {{ tpl $env.value $global | quote }}
              {{- else if $env.valueFrom }}
              valueFrom: {{ tpl (toYaml $env.valueFrom) $global | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.proxySidecar.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.proxySidecar.resources | nindent 12 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- range $env := index .}}
            {{- with $env.configMapRef }}
            - configMapRef:
                name: {{ tpl (required ".name key must be set in configMapRef" .name) $global }}
            {{- end }}
            {{- with $env.secretRef }}
            - secretRef:
                name: {{ tpl (required ".name key must be set on secretRef" .name) $global }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $env := index . }}
            - name: {{ tpl $env.name $global }}
              {{- if $env.value }}
              value: {{ tpl $env.value $global | quote }}
              {{- else if $env.valueFrom }}
              valueFrom: {{ tpl (toYaml $env.valueFrom) $global | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.proxySidecar.enabled }}
          {{- else }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
