{{- if and .Values.virtualService.enabled .Values.virtualService5xxMonitor.enabled }}

{{ $values    := .Values }}
{{ $cluster   := .Values.fullnameOverride }}
{{ $namespace := .Release.Namespace }}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
spec:
  groups:
  - name: {{ .Release.Name }}.{{ .Release.Namespace }}.Rules
    rules:
    - alert: {{ .Release.Name }}-5xx-Rate-Too-High
      annotations:
        summary: High rate of 5xx errors from {{ include "simple-app.fullname" . }}
        runbook_url: "{{ .Values.virtualService5xxMonitor.runbookUrl | default $values.runbookUrl }}"
        description: >-
          High rate of 5xx responses from the  {{ include "simple-app.fullname" . }} VirtualService.
      expr: >-
        sum(increase(istio_requests_total{response_code=~"5.*", destination_service_name="{{ include "simple-app.fullname" . }}"}[60s]))
         / sum(increase(istio_requests_total{destination_service_name="{{ include "simple-app.fullname" . }}"}[60s])) > {{ .Values.virtualService5xxMonitor.threshold }}
      for: {{ .Values.virtualService5xxMonitor.period }}
      labels:
        severity: {{ .Values.virtualService5xxMonitor.severity | default .Values.alerts.severity }}
{{- end }}
