{{- if and (.Values.secrets) (eq .Values.secretsEngine "sealed") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "nd-common.fullname" . }}-secrets
  annotations:
    {{- /* 
    Always (for now) set scope to be namespace-wide. At any time if usecases arise to
    for cluster-wide scope, we can update these template to make it configurable (this
    would also mean a separation of SealedSecret objects if mixing-and-matching) 
    */}}
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "nd-common.fullname" . }}-secrets 
{{- end }}
