{{/*
The Service resource is  created any time the "ports" key has ports. It is
also created any time the Values.monitor.enabled is set true - because we use
a ServiceMonitor in this chart to monitor pods.
*/}}
{{- if or .Values.ports .Values.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nd-common.fullname" . }}
  labels:
    {{- include "nd-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "simple-app.servicePorts" . | nindent 4 }}
    {{- if .Values.monitor.enabled }}
    - port: {{ .Values.monitor.portNumber }}
      targetPort: {{ .Values.monitor.portNumber }}
      name: {{ .Values.monitor.portName }}
    {{- end }}
  selector:
    {{- include "nd-common.selectorLabels" . | nindent 4 }}
{{- end }}
