name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          if [[ "$changed" == *"rollout-app"* ]]; then
            echo "::set-output name=rollout::true"
          fi

      - name: Run chart-testing (lint)
        run: ct --config ct.yaml lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: kindest/node:v1.23.6
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Argo Rollouts Controller
        if: steps.list-changed.outputs.rollout == 'true'
        run: |
          make -C charts/rollout-app install_rollouts

      - name: Install CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: make crds

      - name: Wait
        if: steps.list-changed.outputs.changed == 'true'
        run: sleep 1

      - name: Run chart-testing (install)
        run: ct --config ct.yaml install
