{{- if .Values.ingress.enabled -}}
{{- $fullName := include "simple-app.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.sslRedirect }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {
        "Type": "redirect",
        "RedirectConfig": {
          "Protocol": "HTTPS",
          "Port": "443",
          "StatusCode": "HTTP_301"
        }
      }
    {{- end }}
spec:
  rules:
    - host: {{ tpl .Values.ingress.host . | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  {{- if .Values.ingress.port }}
                  number: {{ .Values.ingress.port }}
                  {{- else }}
                  name: {{ .Values.ingress.portName }}
                  {{- end }}
          {{- if .Values.ingress.sslRedirect }}
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          {{- end }}
  {{- end }}
